// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_owFML-Xq50w_Siz17aBG3UWWzT9vncc',
    appId: '1:23306976251:web:e441b1d0add76e6c7a695e',
    messagingSenderId: '23306976251',
    projectId: 'reddit-clone-3ca40',
    authDomain: 'reddit-clone-3ca40.firebaseapp.com',
    storageBucket: 'reddit-clone-3ca40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRkkvVU7VYpF8xgjC-ACcPLCopm89ynHI',
    appId: '1:23306976251:android:674320e65da8fcf37a695e',
    messagingSenderId: '23306976251',
    projectId: 'reddit-clone-3ca40',
    storageBucket: 'reddit-clone-3ca40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD2cU-WZSdlGOccR7Bw8ZjZmyLaeZn7vk',
    appId: '1:23306976251:ios:71caee90cf7ae5827a695e',
    messagingSenderId: '23306976251',
    projectId: 'reddit-clone-3ca40',
    storageBucket: 'reddit-clone-3ca40.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD2cU-WZSdlGOccR7Bw8ZjZmyLaeZn7vk',
    appId: '1:23306976251:ios:c0b2f301e52bc2517a695e',
    messagingSenderId: '23306976251',
    projectId: 'reddit-clone-3ca40',
    storageBucket: 'reddit-clone-3ca40.appspot.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
